### ISSUE TITLE
sliding_window_min_ff: fails at runtime: out0 not defined (commit 539f2ba1005d)

### ISSUE THREAD

**Issue by alexeicolin** [kicksat/kicksat2gs#2]
```
  File "/home/acolin/dev/edbsat/kicksat2gs/build/pkg/lib/python2.7/site-packages/kicksat2gs/sliding_window_min_ff.py", line 44, in work                                                         
    out0[k] = amin(in0[k:k+self._length])                                                                          
NameError: global name 'out0' is not defined     
```
Any tips for what could be the reason? Thank you!

**Comment by alexeicolin** [comment]
```
diff --git a/python/sliding_window_max_ff.py b/python/sliding_window_max_ff.py
index b5c079d..a59d482 100644
--- a/python/sliding_window_max_ff.py
+++ b/python/sliding_window_max_ff.py
@@ -37,7 +37,7 @@ class sliding_window_max_ff(gr.sync_block):
 
     def work(self, input_items, output_items):
         in0 = input_items[0]
-        out = output_items[0]
+        out0 = output_items[0]
        
        k = 0   
        while k < len(in0):
diff --git a/python/sliding_window_min_ff.py b/python/sliding_window_min_ff.py
index 5760ba5..8e7938b 100644
--- a/python/sliding_window_min_ff.py
+++ b/python/sliding_window_min_ff.py
@@ -37,7 +37,7 @@ class sliding_window_min_ff(gr.sync_block):
 
     def work(self, input_items, output_items):
         in0 = input_items[0]
-        out = output_items[0]
+        out0 = output_items[0]
        
        k = 0   
        while k < len(in0):
```
But now it fails with
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gnuradio/gr/gateway.py", line 55, in eval
    try: self._callback()
  File "/usr/lib/python2.7/site-packages/gnuradio/gr/gateway.py", line 225, in __gr_block_handle
    try: self._callback()
  File "/usr/lib/python2.7/site-packages/gnuradio/gr/gateway.py", line 225, in __gr_block_handle
    ) for i in range(noutputs)],
  File "/home/acolin/dev/edbsat/kicksat2gs/build/pkg/lib/python2.7/site-packages/kicksat2gs/sliding_window_min_ff.py", line 44, in work
    ) for i in range(noutputs)],
  File "/home/acolin/dev/edbsat/kicksat2gs/build/pkg/lib/python2.7/site-packages/kicksat2gs/sliding_window_max_ff.py", line 44, in work
    out0[k] = amin(in0[k:k+self._length])
    out0[k] = amax(in0[k:k+self._length])
IndexError: index 40 is out of bounds for axis 0 with size 40
IndexError: index 111 is out of bounds for axis 0 with size 111
```
I've replaced osmocom Source block with File Source with complex output if that matters.

**Comment by alexeicolin** [comment]
Don't know if this makes any sense, but at least it runs and I can observe an FFT plot:
```
diff --git a/python/sliding_window_max_ff.py b/python/sliding_window_max_ff.py
index b5c079d..36030d6 100644
--- a/python/sliding_window_max_ff.py
+++ b/python/sliding_window_max_ff.py
@@ -37,10 +37,10 @@ class sliding_window_max_ff(gr.sync_block):
 
     def work(self, input_items, output_items):
         in0 = input_items[0]
-        out = output_items[0]
+        out0 = output_items[0]
        
        k = 0   
-       while k < len(in0):
+       while k < len(in0) and k < len(out0):
                out0[k] = amax(in0[k:k+self._length])
                k+=1
 
diff --git a/python/sliding_window_min_ff.py b/python/sliding_window_min_ff.py
index 5760ba5..f5f307c 100644
--- a/python/sliding_window_min_ff.py
+++ b/python/sliding_window_min_ff.py
@@ -37,10 +37,10 @@ class sliding_window_min_ff(gr.sync_block):
 
     def work(self, input_items, output_items):
         in0 = input_items[0]
-        out = output_items[0]
+        out0 = output_items[0]
        
        k = 0   
-       while k < len(in0):
+       while k < len(in0) and k < len(out0):
                out0[k] = amin(in0[k:k+self._length])
                k+=1
```
